---
name: Delete merged branches from all repositories
'on':
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

defaults:
  run:
    shell: nu {0}

jobs:
  delete-merged-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Nu
        uses: hustcer/setup-nu@main
        with:
          version: '0.64.0'
      - run: ./merged-branches.nu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
