# print help message and ant help
extern "ant" [
	--h					# print help message and ant help
	--noconfig					# suppress sourcing of configuration files
	--usejikes					# enable use of jikes by default
	--execdebug					# print ant exec line generated by this launch script
	...args
]