# Show help
extern "apk" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Add packages
extern "apk add" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Remove packages
extern "apk del" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Repair package
extern "apk fix" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Update repository indexes
extern "apk update" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Give detailed information about packages
extern "apk info" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# List packages
extern "apk list" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Search package
extern "apk search" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Upgrade installed packages
extern "apk upgrade" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Manage local package cache
extern "apk cache" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Compare package versions
extern "apk version" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Create repository index file
extern "apk index" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Download packages
extern "apk fetch" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Audit the directories for changes
extern "apk audit" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Verify package integrity and signature
extern "apk verify" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Generate graphviz graphs
extern "apk dot" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Show repository policy for packages
extern "apk policy" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Show statistics about repositories and installations
extern "apk stats" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]

# Show checksums of package contents
extern "apk manifest" [
	--help(-h)					# Show help
	--quiet(-q)					# Print less information
	--verbose(-v)					# Print more information
	--interactive(-i)					# Ask confirmation for certain operations
	--version(-V)					# Print program version
	--force-binary-stdout					# Continue even if binary data is to be output
	--force-broken-world					# Continue even if 'world' cannot be satisfied
	--force-non-repository					# Continue even if packages may be lost on reboot
	--force-old-apk					# Continue even if packages use unsupported features
	--force-overwrite					# Overwrite files in other packages
	--force-refresh					# Don't use cached files
	--update-cache(-U)					# Alias for --cache-max-age 1
	--progress					# Show a progress bar
	--no-progress					# Disable progress bar even for TTYs
	--purge					# Delete also modified configuration files and uninstalled packages from cache
	--allow-untrusted					# Install packages with untrusted signature or no signature
	--no-network					# Don't use network
	--no-cache					# Don't use any local cache path
	--print-arch					# Print default architecture
	--simulate(-s)					# Simulate the requested operation
	--clean-protected					# Don't create .apk-new files
	--overlay-from-stdin					# Read list of overlay files from stdin
	--no-scripts					# Don't execute any scripts
	--no-commit-hooks					# Skip pre/post hook scripts
	--initramfs-diskless-boot					# Enables options for diskless initramfs boot
	--initdb					# Initialize database
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--no-chown					# Don't change file owner or group
	--rdepends(-r)					# Remove unneeded dependencies too
	--depends(-d)					# Fix all dependencies too
	--reinstall(-r)					# Reinstall the package
	--upgrade(-u)					# Prefer to upgrade package
	--xattr(-x)					# Fix packages with broken xattrs
	--directory-permissions					# Reset all directory permissions
	--contents(-L)					# List included files
	--installed(-e)					# Check PACKAGE installed status
	--depends(-R)					# List the dependencies
	--provides(-P)					# List virtual packages provided
	--rdepends(-r)					# List reverse dependencies
	--replaces					# List packages that PACKAGE might replace
	--install-if					# List install_if rule
	--rinstall-if					# List packages having install_if referencing PACKAGE
	--webpage(-w)					# Print the URL for the upstream
	--size(-s)					# Show installed size
	--description(-d)					# Print the description
	--license					# Print the license
	--triggers					# Print active triggers
	--all(-a)					# Print all information
	--installed(-I)					# List installed packages only
	--orphaned(-O)					# List orphaned packages only
	--available(-a)					# List available packages only
	--upgradable(-u)					# List upgradable packages only
	--origin(-o)					# List packages by origin
	--depends(-d)					# List packages by dependency
	--providers(-P)					# List packages by provider
	--all(-a)					# Show all package versions
	--description(-d)					# Search package descriptions
	--exact(-x)					# Require exact match
	--origin(-o)					# Print origin package name
	--rdepends(-r)					# Print reverse dependencies
	--has-origin					# List packages that have the given origin
	--available(-a)					# Reset all packages to the provided versions
	--latest(-l)					# Select latest version of package
	--no-self-upgrade					# Don't do early upgrade of the apk
	--self-upgrade-only					# Only do self-upgrade
	--ignore					# Ignore the upgrade of PACKAGE
	--prune					# Prune the WORLD by removing packages which are no longer available
	--upgrade(-u)					# Prefer to upgrade package
	--latest(-l)					# Select latest version of package
	--indexes(-I)					# Print description and versions of indexes
	--test(-t)					# Compare two given versions
	--check(-c)					# Check the given version strings
	--all(-a)					# Consider packages from all repository tags
	--no-warnings					# Disable the warning about missing dependencies
	--link(-L)					# Create hard links
	--recursive(-R)					# Fetch all dependencies too
	--simulate					# Simulate the requested operation
	--stdout(-s)					# Dump the .apk to stdout
	--backup					# Audit configuration files only
	--system					# Audit all system files
	--check-permissions					# Check file permissions too
	--recursive(-r)					# Descend into directories and audit them as well
	--packages					# List only the changed packages
	--errors					# Consider only packages with errors
	--installed					# Consider only installed packages
	...args
]