# returns the name of the current branch
export def git_current_branch [] {
    ^git rev-parse --abbrev-ref HEAD
}

export def git_main_branch [] {
    git remote show origin
    | lines
    | str trim
    | find --regex 'HEAD .*?[：: ].+'
    | first
    | ansi strip
    | str replace --regex 'HEAD .*?[：: ]\s*(.+)' '$1'
}

#
# Abbreviations
# (sorted alphabetically)
#

const git_abbreviations = {
    ga: "git add"
    gaa: "git add --all"
    gapa: "git add --patch"
    gau: "git add --update"
    gav: "git add --verbose"
    gap: "git apply"
    gapt: "git apply --3way"
    gb: "git branch"
    gba: "git branch --all"
    gbd: "git branch --delete"
    gbD: "git branch --delete --force"
    gbl: "git blame -b -w"
    gbm: "git branch --move"
    gbmc: "git branch --move (git_current_branch)"
    gbnm: "git branch --no-merged"
    gbr: "git branch --remote"
    gbs: "git bisect"
    gbsb: "git bisect bad"
    gbsg: "git bisect good"
    gbsn: "git bisect new"
    gbso: "git bisect old"
    gbsr: "git bisect reset"
    gbss: "git bisect start"
    gc: "git commit --verbose"
    gc!: "git commit --verbose --amend"
    gcn: "git commit --verbose --no-edit"
    gcn!: "git commit --verbose --no-edit --amend"
    gca: "git commit --verbose --all"
    gca!: "git commit --verbose --all --amend"
    gcan!: "git commit --verbose --all --no-edit --amend"
    gcans!: "git commit --verbose --all --signoff --no-edit --amend"
    gcam: "git commit --all --message"
    gcas: "git commit --all --signoff"
    gcasm: "git commit --all --signoff --message"
    gcb: "git checkout -b"
    gcd: "git checkout develop"
    gcf: "git config --list"
    gcl: "git clone --recurse-submodules"
    gclean: "git clean --interactive -d"
    gpristine: "git reset --hard; git clean -d --force -x"
    gcm: "git checkout (git_main_branch)"
    gcmsg: "git commit --message"
    gco: "git checkout"
    gcor: "git checkout --recurse-submodules"
    gcount: "git shortlog --summary --numbered"
    gcp: "git cherry-pick"
    gcpa: "git cherry-pick --abort"
    gcpc: "git cherry-pick --continue"
    gcs: "git commit --gpg-sign"
    gcss: "git commit --gpg-sign --signoff"
    gcssm: "git commit --gpg-sign --signoff --message"
    gd: "git diff"
    gdca: "git diff --cached"
    gdcw: "git diff --cached --word-diff"
    gdct: "git describe --tags (git rev-list --tags --max-count=1)"
    gds: "git diff --staged"
    gdt: "git diff-tree --no-commit-id --name-only -r"
    gdup: "git diff @{upstream}"
    gdw: "git diff --word-diff"
    gf: "git fetch"
    gfa: "git fetch --all --prune"
    gfo: "git fetch origin"
    gg: "git gui citool"
    gga: "git gui citool --amend"
    ghh: "git help"
    gignore: "git update-index --assume-unchanged"
    gl: "git log"
    glg: "git log --stat"
    glgp: "git log --stat --patch"
    glgg: "git log --graph"
    glgga: "git log --graph --decorate --all"
    glgm: "git log --graph --max-count=10"
    glo: "git log --oneline --decorate"
    glod: "git log --graph $'--pretty=%Cred%h%Creset -%C(char lp)auto(char rp)%d%Creset %s %Cgreen(char lp)%ad(char rp) %C(char lp)bold blue(char rp)<%an>%Creset'"
    glods: "git log --graph $'--pretty=%Cred%h%Creset -%C(char lp)auto(char rp)%d%Creset %s %Cgreen(char lp)%ad(char rp) %C(char lp)bold blue(char rp)<%an>%Creset' --date=short"
    glog: "git log --oneline --decorate --graph"
    gloga: "git log --oneline --decorate --graph --all"
    glol: "git log --graph $'--pretty=%Cred%h%Creset -%C(char lp)auto(char rp)%d%Creset %s %Cgreen(char lp)%ar(char rp) %C(char lp)bold blue(char rp)<%an>%Creset'"
    glola: "git log --graph $'--pretty=%Cred%h%Creset -%C(char lp)auto(char rp)%d%Creset %s %Cgreen(char lp)%ar(char rp) %C(char lp)bold blue(char rp)<%an>%Creset' --all"
    glols: "git log --graph $'--pretty=%Cred%h%Creset -%C(char lp)auto(char rp)%d%Creset %s %Cgreen(char lp)%ar(char rp) %C(char lp)bold blue(char rp)<%an>%Creset' --stat"
    gm: "git merge"
    gmtl: "git mergetool --no-prompt"
    gmtlvim: "git mergetool --no-prompt --tool=vimdiff"
    gma: "git merge --abort"
    gmom: "git merge $\"origin/(git_main_branch)\""
    gp: "git push"
    gpd: "git push --dry-run"
    gpf: "git push --force-with-lease"
    gpf!: "git push --force"
    gpl: "git pull"
    gpoat: "git push origin --all; git push origin --tags"
    gpod: "git push origin --delete"
    gpodc: "git push origin --delete (git_current_branch)"
    gpr: "git pull --rebase"
    gpu: "git push upstream"
    gpv: "git push --verbose"
    gr: "git remote"
    gpra: "git pull --rebase --autostash"
    gprav: "git pull --rebase --autostash --verbose"
    gprv: "git pull --rebase --verbose"
    gpsup: "git push --set-upstream origin (git_current_branch)"
    gra: "git remote add"
    grb: "git rebase"
    grba: "git rebase --abort"
    grbc: "git rebase --continue"
    grbd: "git rebase develop"
    grbi: "git rebase --interactive"
    grbm: "git rebase (git_main_branch)"
    grbo: "git rebase --onto"
    grbs: "git rebase --skip"
    grev: "git revert"
    grh: "git reset"
    grhh: "git reset --hard"
    groh: "git reset $\"origin/(git_current_branch)\" --hard"
    grm: "git rm"
    grmc: "git rm --cached"
    grmv: "git remote rename"
    grrm: "git remote remove"
    grs: "git restore"
    grset: "git remote set-url"
    grss: "git restore --source"
    grst: "git restore --staged"
    grt: "cd (git rev-parse --show-toplevel | complete | if $in.exit_code == 0 { $in.stdout | str trim } else { '.' })"
    gru: "git reset --"
    grup: "git remote update"
    grv: "git remote --verbose"
    gsb: "git status --short --branch"
    gsd: "git svn dcommit"
    gsh: "git show"
    gshs: "git show -s"
    gsi: "git submodule init"
    gsps: "git show --pretty=short --show-signature"
    gsr: "git svn rebase"
    gss: "git status --short"
    gst: "git status"
    gsta: "git stash push"
    gstaa: "git stash apply"
    gstc: "git stash clear"
    gstd: "git stash drop"
    gstl: "git stash list"
    gstp: "git stash pop"
    gsts: "git stash show --text"
    gstu: "gsta --include-untracked"
    gstall: "git stash --all"
    gsu: "git submodule update"
    gsw: "git switch"
    gswc: "git switch --create"
    gts: "git tag --sign"
    gtv: "git tag | lines | sort"
    glum: "git pull upstream (git_main_branch)"
    gunignore: "git update-index --no-assume-unchanged"
    gup: "git pull --rebase"
    gupv: "git pull --rebase --verbose"
    gupa: "git pull --rebase --autostash"
    gupav: "git pull --rebase --autostash --verbose"
    gwch: "git whatchanged -p --abbrev-commit --pretty=medium"
    gwt: "git worktree"
    gwtls: "git worktree list"
    gwtmv: "git worktree move"
    gwtm: "git worktree remove"
    gam: "git am"
    gamc: "git am --continue"
    gams: "git am --skip"
    gama: "git am --abort"
    gamscp: "git am --show-current-patch"
}

export-env {
    $env.config.abbreviations = {
        ...$git_abbreviations
        ...$env.config.abbreviations
    }
}
