export use completions/7z.nu *
export use completions/7za.nu *
export use completions/7zr.nu *
export use completions/VBoxHeadless.nu *
export use completions/VBoxSDL.nu *
export use completions/a2disconf.nu *
export use completions/a2dismod.nu *
export use completions/a2dissite.nu *
export use completions/a2enconf.nu *
export use completions/a2enmod.nu *
export use completions/a2ensite.nu *
export use completions/abbr.nu *
export use completions/abook.nu *
export use completions/acat.nu *
export use completions/ack.nu *
export use completions/acpi.nu *
export use completions/adduser.nu *
export use completions/adiff.nu *
export use completions/alias.nu *
export use completions/als.nu *
export use completions/alsactl.nu *
export use completions/alsamixer.nu *
export use completions/alternatives.nu *
export use completions/amixer.nu *
export use completions/and.nu *
export use completions/animate.nu *
export use completions/ansible-galaxy.nu *
export use completions/ansible-playbook.nu *
export use completions/ansible-vault.nu *
export use completions/ansible.nu *
export use completions/ant.nu *
export use completions/apack.nu *
export use completions/apk.nu *
export use completions/apropos.nu *
export use completions/apt-build.nu *
export use completions/apt-cache.nu *
export use completions/apt-cdrom.nu *
export use completions/apt-config.nu *
export use completions/apt-extracttemplates.nu *
export use completions/apt-file.nu *
export use completions/apt-ftparchive.nu *
export use completions/apt-get.nu *
export use completions/apt-key.nu *
export use completions/apt-listbugs.nu *
export use completions/apt-listchanges.nu *
export use completions/apt-mark.nu *
export use completions/apt-move.nu *
export use completions/apt-proxy-import.nu *
export use completions/apt-rdepends.nu *
export use completions/apt-setup.nu *
export use completions/apt-show-source.nu *
export use completions/apt-show-versions.nu *
export use completions/apt-sortpkgs.nu *
export use completions/apt-spy.nu *
export use completions/apt-src.nu *
export use completions/apt-zip-inst.nu *
export use completions/apt-zip-list.nu *
export use completions/apt.nu *
export use completions/aptitude.nu *
export use completions/arc.nu *
export use completions/archlinux-java.nu *
export use completions/arepack.nu *
export use completions/arp.nu *
export use completions/as.nu *
export use completions/asciidoctor.nu *
export use completions/at.nu *
export use completions/atd.nu *
export use completions/atom.nu *
export use completions/atool.nu *
export use completions/atq.nu *
export use completions/atrm.nu *
export use completions/attrib.nu *
export use completions/aunpack.nu *
export use completions/aura.nu *
export use completions/avifdec.nu *
export use completions/avifenc.nu *
export use completions/aws.nu *
export use completions/badblocks.nu *
export use completions/base64.nu *
export use completions/bb-wrapper.nu *
export use completions/bc.nu *
export use completions/bd.nu *
export use completions/begin.nu *
export use completions/bg.nu *
export use completions/bind.nu *
export use completions/bison.nu *
export use completions/black.nu *
export use completions/block.nu *
export use completions/bluetoothctl.nu *
export use completions/bootctl.nu *
export use completions/bosh.nu *
export use completions/break.nu *
export use completions/btrfs.nu *
export use completions/builtin.nu *
export use completions/bundle.nu *
export use completions/bunzip2.nu *
export use completions/busctl.nu *
export use completions/bzcat.nu *
export use completions/bzip2.nu *
export use completions/bzr.nu *
export use completions/cabal-dev.nu *
export use completions/caddy.nu *
export use completions/caffeinate.nu *
export use completions/camcontrol.nu *
export use completions/cancel.nu *
export use completions/canto.nu *
export use completions/cargo.nu *
export use completions/castnow.nu *
export use completions/cd.nu *
export use completions/cdh.nu *
export use completions/cdrecord.nu *
export use completions/cf.nu *
export use completions/choice.nu *
export use completions/chronyc.nu *
export use completions/chsh.nu *
export use completions/cjxl.nu *
export use completions/clasp.nu *
export use completions/clean.nu *
export use completions/cleanmgr.nu *
export use completions/climate.nu *
export use completions/cmark.nu *
export use completions/cmd.nu *
export use completions/cmdkey.nu *
export use completions/code.nu *
export use completions/colordiff.nu *
export use completions/colorsvn.nu *
export use completions/combine.nu * *
export use completions/command.nu *
export use completions/commandline.nu *
export use completions/comp.nu *
export use completions/compare.nu *
export use completions/complete.nu *
export use completions/composer.nu *
export use completions/composite.nu *
export use completions/conda.nu *
export use completions/configure.nu *
export use completions/conjure.nu *
export use completions/connmanctl.nu *
export use completions/continue.nu *
export use completions/convert.nu *
export use completions/coredumpctl.nu *
export use completions/cowsay.nu *
export use completions/cowthink.nu *
export use completions/cpupower.nu *
export use completions/create_ap.nu *
export use completions/createdb.nu *
export use completions/cryptsetup.nu *
export use completions/csc.nu *
export use completions/csi.nu *
export use completions/cupsdisable.nu *
export use completions/cupsenable.nu *
export use completions/curl.nu *
export use completions/cvs.nu *
export use completions/cwebp.nu *
export use completions/cygpath.nu *
export use completions/cygport.nu *
export use completions/cygstart.nu *
export use completions/darcs.nu *
export use completions/dart.nu *
export use completions/date.nu *
export use completions/dconf.nu *
export use completions/dd.nu *
export use completions/defaults.nu *
export use completions/dhclient.nu *
export use completions/dhcpcd.nu *
export use completions/diff.nu *
export use completions/dig.nu *
export use completions/diskutil.nu *
export use completions/display.nu *
export use completions/djxl.nu *
export use completions/dlocate.nu *
export use completions/dm-tool.nu *
export use completions/dmesg.nu *
export use completions/dnf.nu *
export use completions/doas.nu *
export use completions/dotnet.nu *
export use completions/downgrade.nu *
export use completions/dpkg-reconfigure.nu *
export use completions/dpkg.nu *
export use completions/dropdb.nu *
export use completions/dscacheutil.nu *
export use completions/du.nu *
export use completions/dumpcap.nu *
export use completions/dvipdfm.nu *
export use completions/ebuild.nu *
export use completions/echo.nu *
export use completions/egrep.nu *
export use completions/eix-sync.nu *
export use completions/eix.nu *
export use completions/elatex.nu *
export use completions/elixir.nu *
export use completions/elvish.nu *
export use completions/emacs.nu *
export use completions/emaint.nu *
export use completions/emerge.nu *
export use completions/encfs.nu *
export use completions/entr.nu *
export use completions/eopkg.nu *
export use completions/epkginfo.nu *
export use completions/equery.nu *
export use completions/etex.nu *
export use completions/ethtool.nu *
export use completions/eval.nu *
export use completions/evince.nu *
export use completions/exec.nu *
export use completions/exercism.nu *
export use completions/exit.nu *
export use completions/expand.nu *
export use completions/fab.nu *
export use completions/fastboot.nu *
export use completions/feh.nu *
export use completions/ffmpeg.nu *
export use completions/ffplay.nu *
export use completions/ffprobe.nu *
export use completions/fg.nu *
export use completions/fgrep.nu *
export use completions/figlet.nu *
export use completions/file.nu *
export use completions/find.nu *
export use completions/firewall-cmd.nu *
export use completions/fish.nu *
export use completions/fish_add_path.nu *
export use completions/fish_indent.nu *
export use completions/fish_key_reader.nu *
export use completions/flac.nu *
export use completions/flatpak.nu *
export use completions/fluxbox-remote.nu *
export use completions/for.nu *
export use completions/forfiles.nu *
export use completions/fossil.nu *
export use completions/fsharpc.nu *
export use completions/fsharpi.nu *
export use completions/funced.nu *
export use completions/funcsave.nu *
export use completions/function.nu *
export use completions/functions.nu *
export use completions/fuser.nu *
export use completions/fusermount.nu *
export use completions/fzf.nu *
export use completions/g++.nu *
export use completions/gacutil.nu *
export use completions/gapplication.nu *
export use completions/gcc.nu *
export use completions/gdb.nu *
export use completions/gdbus.nu *
export use completions/gem.nu *
export use completions/gendarme.nu *
export use completions/gio.nu * *
export use completions/git-sizer.nu *
export use completions/git.nu *
export use completions/gitk.nu *
export use completions/gnome-extensions.nu *
export use completions/go.nu *
export use completions/godoc.nu *
export use completions/gofmt.nu *
export use completions/goimports.nu *
export use completions/golint.nu *
export use completions/gorename.nu *
export use completions/gpasswbd.nu *
export use completions/gphoto2.nu *
export use completions/gping.nu *
export use completions/gprof.nu *
export use completions/grep.nu *
export use completions/gresource.nu *
export use completions/groupadd.nu *
export use completions/groups.nu *
export use completions/grub-file.nu *
export use completions/grub-install.nu *
export use completions/grub-mkrescue.nu *
export use completions/grunt.nu *
export use completions/gsettings.nu *
export use completions/gunzip.nu *
export use completions/gv.nu *
export use completions/gvim.nu *
export use completions/gvimdiff.nu *
export use completions/gzip.nu *
export use completions/hashcat.nu *
export use completions/heroku.nu *
export use completions/hg.nu *
export use completions/highlight.nu *
export use completions/hikari.nu *
export use completions/history.nu *
export use completions/hjson.nu *
export use completions/hledger.nu *
export use completions/homectl.nu *
export use completions/hostnamectl.nu *
export use completions/htop.nu *
export use completions/hugo.nu *
export use completions/hwinfo.nu *
export use completions/i3-msg.nu *
export use completions/icdiff.nu *
export use completions/iconv.nu *
export use completions/identify.nu *
export use completions/iex.nu *
export use completions/if.nu *
export use completions/ifdata.nu *
export use completions/ifdown.nu *
export use completions/ifup.nu *
export use completions/ikdasm.nu *
export use completions/ilasm.nu *
export use completions/import.nu *
export use completions/imv.nu *
export use completions/invoke-rc.d.nu *
export use completions/ip.nu *
export use completions/irb.nu *
export use completions/iw.nu *
export use completions/jbake.nu *
export use completions/jest.nu *
export use completions/jhipster.nu *
export use completions/jobs.nu *
export use completions/john.nu *
export use completions/journalctl.nu *
export use completions/jq.nu *
export use completions/julia.nu *
export use completions/k3d.nu *
export use completions/kak.nu *
export use completions/kcmshell5.nu *
export use completions/kdeconnect-cli.nu *
export use completions/keepassxc-cli.nu *
export use completions/keybase.nu *
export use completions/kill.nu *
export use completions/killall.nu *
export use completions/kitchen.nu *
export use completions/kldload.nu *
export use completions/kldunload.nu *
export use completions/latex.nu *
export use completions/latexmk.nu *
export use completions/ldapsearch.nu *
export use completions/lein.nu *
export use completions/less.nu *
export use completions/light.nu *
export use completions/lightdm.nu *
export use completions/ln.nu *
export use completions/localectl.nu *
export use completions/locate.nu *
export use completions/loginctl.nu *
export use completions/logkeys.nu *
export use completions/losetup.nu *
export use completions/lp.nu *
export use completions/lpadmin.nu *
export use completions/lpinfo.nu *
export use completions/lpoptions.nu *
export use completions/lppasswd.nu *
export use completions/lpq.nu *
export use completions/lpr.nu *
export use completions/lpstat.nu *
export use completions/ls.nu *
export use completions/lsblk.nu *
export use completions/lscpu.nu *
export use completions/lsof.nu *
export use completions/lsusb.nu *
export use completions/lua.nu *
export use completions/lualatex.nu *
export use completions/lunchy.nu *
export use completions/lxpanel.nu *
export use completions/lz4.nu *
export use completions/lz4c.nu *
export use completions/lz4cat.nu *
export use completions/m4.nu *
export use completions/machinectl.nu *
export use completions/make.nu *
export use completions/makedepend.nu *
export use completions/makensis.nu *
export use completions/makepkg.nu *
export use completions/man.nu *
export use completions/mariner.nu *
export use completions/matlab.nu *
export use completions/mc.nu *
export use completions/md5sum.nu *
export use completions/mdadm.nu *
export use completions/mdbook.nu *
export use completions/mddiagnose.nu *
export use completions/mdimport.nu *
export use completions/mdls.nu *
export use completions/mdutil.nu *
export use completions/meson.nu *
export use completions/micro.nu *
export use completions/minikube.nu *
export use completions/mix.nu *
export use completions/mkbundle.nu *
export use completions/mkdocs.nu *
export use completions/mkdosfs.nu *
export use completions/mkfs.fat.nu *
export use completions/mkfs.vfat.nu *
export use completions/mkinitcpio.nu *
export use completions/mkpasswd.nu *
export use completions/mkvextract.nu *
export use completions/mocha.nu *
export use completions/mocp.nu *
export use completions/modinfo.nu *
export use completions/modprobe.nu *
export use completions/mogrify.nu *
export use completions/mono.nu *
export use completions/monodis.nu *
export use completions/monop.nu *
export use completions/montage.nu *
export use completions/mosh.nu *
export use completions/mount.nu *
export use completions/mpc.nu *
export use completions/mplayer.nu *
export use completions/mpv.nu *
export use completions/msfconsole.nu *
export use completions/msfdb.nu *
export use completions/msfvenom.nu *
export use completions/msgfmt.nu *
export use completions/mtr.nu *
export use completions/mupdf.nu *
export use completions/mutt.nu *
export use completions/mvn.nu *
export use completions/mysql.nu *
export use completions/namei.nu *
export use completions/native2ascii.nu *
export use completions/ncat.nu *
export use completions/ncdu.nu *
export use completions/netctl-auto.nu *
export use completions/netctl.nu *
export use completions/nethack.nu *
export use completions/networkctl.nu *
export use completions/nextd.nu *
export use completions/ng.nu *
export use completions/ngrok.nu *
export use completions/nice.nu *
export use completions/ninja.nu *
export use completions/nl.nu *
export use completions/nm.nu *
export use completions/nmap.nu *
export use completions/nmcli.nu *
export use completions/node.nu *
export use completions/nodeenv.nu *
export use completions/not.nu *
export use completions/npm.nu *
export use completions/nvim.nu *
export use completions/nvram.nu *
export use completions/objdump.nu *
export use completions/obnam.nu *
export use completions/octave.nu *
export use completions/oggenc.nu *
export use completions/omega.nu *
export use completions/opam.nu *
export use completions/openocd.nu *
export use completions/opkg.nu *
export use completions/optimus-manager.nu *
export use completions/or.nu *
export use completions/p4.nu *
export use completions/pacaur.nu *
export use completions/pacman-color.nu *
export use completions/pacman-key.nu *
export use completions/pacman.nu *
export use completions/pacmatic.nu *
export use completions/pacmd.nu *
export use completions/pactl.nu *
export use completions/pactree.nu *
export use completions/pandoc.nu *
export use completions/patch.nu *
export use completions/patool.nu *
export use completions/pbget.nu *
export use completions/pdfelatex.nu *
export use completions/pdfetex.nu *
export use completions/pdflatex.nu *
export use completions/pdftex.nu *
export use completions/pdftotext.nu *
export use completions/perl.nu *
export use completions/pfctl.nu *
export use completions/pg_dump.nu *
export use completions/pg_dumpall.nu *
export use completions/pg_restore.nu *
export use completions/pgrep.nu *
export use completions/phpunit.nu *
export use completions/pidof.nu *
export use completions/pine.nu *
export use completions/ping.nu *
export use completions/pinky.nu *
export use completions/pkg-config.nu *
export use completions/pkg.nu *
export use completions/pkg_add.nu *
export use completions/pkg_delete.nu *
export use completions/pkgadd.nu *
export use completions/pkgfile.nu *
export use completions/pkgmk.nu *
export use completions/pkgrm.nu *
export use completions/plutil.nu *
export use completions/poff.nu *
export use completions/pon.nu *
export use completions/port.nu *
export use completions/portmaster.nu *
export use completions/ports.nu *
export use completions/poweroff.nu *
export use completions/powerpill.nu *
export use completions/prevd.nu *
export use completions/prt-get.nu *
export use completions/ps.nu *
export use completions/psql.nu *
export use completions/pstack.nu *
export use completions/psub.nu *
export use completions/pv.nu *
export use completions/pydf.nu *
export use completions/pyenv.nu *
export use completions/pygmentize.nu *
export use completions/python.nu *
export use completions/python2.nu *
export use completions/python3.nu *
export use completions/pzstd.nu *
export use completions/qubes-gpg-client.nu *
export use completions/quilt.nu *
export use completions/rakudo.nu *
export use completions/random.nu *
export use completions/ranger.nu *
export use completions/rbenv.nu *
export use completions/rc-service.nu *
export use completions/rc-status.nu *
export use completions/rcctl.nu *
export use completions/read.nu *
export use completions/readlink.nu *
export use completions/realpath.nu *
export use completions/rejmerge.nu *
export use completions/renice.nu *
export use completions/resolvectl.nu *
export use completions/return.nu *
export use completions/rfkill.nu *
export use completions/rgrep.nu *
export use completions/rmdir.nu *
export use completions/rmmod.nu *
export use completions/root.nu *
export use completions/roswell.nu *
export use completions/rpm.nu *
export use completions/rst2html4.nu *
export use completions/rst2odt.nu *
export use completions/rst2pseudoxml.nu *
export use completions/rst2s5.nu *
export use completions/rst2xml.nu *
export use completions/rstpep2html.nu *
export use completions/rsync.nu *
export use completions/ruby-build.nu *
export use completions/ruby.nu *
export use completions/rustc.nu *
export use completions/rustup.nu *
export use completions/s3cmd.nu *
export use completions/sass-convert.nu *
export use completions/sass.nu *
export use completions/sbcl.nu *
export use completions/sbt.nu *
export use completions/scanimage.nu *
export use completions/schtasks.nu *
export use completions/scons.nu *
export use completions/scp.nu *
export use completions/screen.nu *
export use completions/scrot.nu *
export use completions/scss.nu *
export use completions/service.nu *
export use completions/set.nu *
export use completions/set_color.nu *
export use completions/setfacl.nu *
export use completions/setsid.nu *
export use completions/setx.nu *
export use completions/setxkbmap.nu *
export use completions/sfdx.nu *
export use completions/sftp.nu *
export use completions/sha1sum.nu *
export use completions/sha224sum.nu *
export use completions/sha256sum.nu *
export use completions/sha384sum.nu *
export use completions/sha512sum.nu *
export use completions/signify.nu *
export use completions/sort.nu *
export use completions/source.nu *
export use completions/speedtest-cli.nu *
export use completions/speedtest.nu *
export use completions/sphinx-apidoc.nu *
export use completions/sphinx-autogen.nu *
export use completions/sphinx-build.nu *
export use completions/sphinx-quickstart.nu *
export use completions/sqlsharp.nu *
export use completions/src.nu *
export use completions/ssh.nu *
export use completions/sshfs.nu *
export use completions/stack.nu *
export use completions/status.nu *
export use completions/strace.nu *
export use completions/stream.nu *
export use completions/string.nu *
export use completions/su.nu *
export use completions/subl.nu *
export use completions/sudo.nu *
export use completions/sv.nu *
export use completions/svn.nu *
export use completions/sylpheed.nu *
export use completions/synclient.nu *
export use completions/sysbench.nu *
export use completions/systemctl.nu *
export use completions/systemd-analyze.nu *
export use completions/systemd-nspawn.nu *
export use completions/tar.nu *
export use completions/tcpdump.nu *
export use completions/tee.nu *
export use completions/telnet.nu *
export use completions/termite.nu *
export use completions/terraform.nu *
export use completions/test.nu *
export use completions/tex.nu *
export use completions/tig.nu *
export use completions/time.nu *
export use completions/timedatectl.nu *
export use completions/timeout.nu *
export use completions/tmutil.nu *
export use completions/tmux.nu *
export use completions/tokei.nu *
export use completions/top.nu *
export use completions/topgrade.nu *
export use completions/totem.nu *
export use completions/tracepath.nu *
export use completions/traceroute.nu *
export use completions/transmission-remote.nu *
export use completions/trap.nu *
export use completions/travis.nu *
export use completions/tree.nu *
export use completions/tsc.nu *
export use completions/tshark.nu *
export use completions/ttx.nu *
export use completions/type.nu *
export use completions/udevadm.nu *
export use completions/udisksctl.nu *
export use completions/ulimit.nu *
export use completions/umount.nu *
export use completions/unexpand.nu *
export use completions/unlz4.nu *
export use completions/unzip.nu *
export use completions/unzstd.nu *
export use completions/update-eix-remote.nu *
export use completions/update-eix.nu *
export use completions/useradd.nu *
export use completions/userdbctl.nu *
export use completions/usermod.nu *
export use completions/vagrant.nu *
export use completions/valgrind.nu *
export use completions/vared.nu *
export use completions/vbc.nu *
export use completions/vim-addons.nu *
export use completions/vim.nu *
export use completions/vimdiff.nu *
export use completions/vips.nu *
export use completions/virsh.nu *
export use completions/vmctl.nu *
export use completions/w.nu *
export use completions/wait.nu *
export use completions/wajig.nu *
export use completions/watch.nu *
export use completions/wesnoth.nu *
export use completions/wg-quick.nu *
export use completions/wget.nu *
export use completions/whatis.nu *
export use completions/while.nu *
export use completions/who.nu *
export use completions/wicd-cli.nu *
export use completions/wicd-client.nu *
export use completions/wicd-gtk.nu *
export use completions/windscribe.nu *
export use completions/wine.nu *
export use completions/wineboot.nu *
export use completions/winemaker.nu *
export use completions/wireshark.nu *
export use completions/wslpath.nu *
export use completions/wvdial.nu *
export use completions/xargs.nu *
export use completions/xbps-alternatives.nu *
export use completions/xbps-checkvers.nu *
export use completions/xbps-create.nu *
export use completions/xbps-dgraph.nu *
export use completions/xbps-digest.nu *
export use completions/xbps-fbulk.nu *
export use completions/xbps-fetch.nu *
export use completions/xbps-install.nu *
export use completions/xbps-pkgdb.nu *
export use completions/xbps-query.nu *
export use completions/xbps-reconfigure.nu *
export use completions/xbps-remove.nu *
export use completions/xbps-rindex.nu *
export use completions/xbps-uchroot.nu *
export use completions/xbps-uhelper.nu *
export use completions/xclip.nu *
export use completions/xdg-mime.nu *
export use completions/xelatex.nu *
export use completions/xgettext.nu *
export use completions/xinput.nu *
export use completions/xmms.nu *
export use completions/xpdf.nu *
export use completions/xprop.nu *
export use completions/xrandr.nu *
export use completions/xrdb.nu *
export use completions/xsel.nu *
export use completions/xsp.nu *
export use completions/xsv.nu *
export use completions/xterm.nu *
export use completions/xxh128sum.nu *
export use completions/xxh32sum.nu *
export use completions/xxh64sum.nu *
export use completions/xxhsum.nu *
export use completions/xz.nu *
export use completions/yadm.nu *
export use completions/yaourt.nu *
export use completions/yarn.nu *
export use completions/yast2.nu *
export use completions/yum.nu *
export use completions/zcat.nu *
export use completions/zef.nu *
export use completions/zfs.nu *
export use completions/zip.nu *
export use completions/zopfli.nu *
export use completions/zopflipng.nu *
export use completions/zpaq.nu *
export use completions/zpool.nu *
export use completions/zstd.nu *
export use completions/zstdcat.nu *
export use completions/zstdgrep.nu *
export use completions/zstdless.nu *
export use completions/zstdmt.nu *
export use completions/zypper.nu *
